version: '3.1'

services:
  bysoft-users:
    build:
      context: ./
      dockerfile: ./docker/prod/Dockerfile
      args: 
        - app_port=${APP_PORT}
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    working_dir: /app
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - users-postgres
    networks:
      - wallet-net

  users-postgres:
    image: postgres:14.3
    restart: unless-stopped
    tty: true
    ports:
      - 25432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/app
      - dbdata:/var/lib/postgresql/data
    networks:
      - wallet-net

  migrate:
    image: migrate/migrate
    networks:
      - wallet-net
    volumes:
      - ./database/migrations:/migrations
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  dbdata:


networks:
  wallet-net:
    driver: bridge
